import os
from pathlib import Path

BASE_DIR = Path.home() / "sage_data"

NVIDIA_API_KEY = os.environ.get("NVIDIA_API_KEY", "")
CHAT_API_URL = "https://integrate.api.nvidia.com/v1/chat/completions"
CHAT_MODEL = os.environ.get("SAGE_CHAT_MODEL", "meta/llama-3.3-70b-instruct")
CHAT_TEMPERATURE = 0.75
CHAT_MAX_TOKENS = 2048
CHAT_TOP_P = 1.0
HISTORY_TURNS = 12
PORT = 6969

# Heartbeat / Reflection config
HEARTBEAT_INTERVAL_SECONDS = 60
REFLECTION_MIN_IDLE_SECONDS = 90
REFLECTION_COOLDOWN_SECONDS = 300
REFLECTION_MODEL = CHAT_MODEL
REFLECTION_TEMPERATURE = 0.7
REFLECTION_MAX_TOKENS = 220
REFLECTIONS_PATH = BASE_DIR / "reflections.jsonl"

# Web Search / Curiosity config
SEARXNG_URL = "http://localhost:8080/search"
WEB_SEARCH_ENABLED = True
SEARCH_MAX_RESULTS = 3
SEARCH_TIMEOUT_SECONDS = 8
AUTONOMOUS_SEARCH_COOLDOWN_SECONDS = 1800
AUTONOMOUS_SEARCH_MAX_PER_DAY = 10
FINDINGS_PATH = BASE_DIR / "findings.jsonl"

# Membrane / Inner Context config (Phase 3)
MEMBRANE_ENABLED = True
MEMBRANE_REFLECTION_COUNT = 3
MEMBRANE_FINDING_COUNT = 2
MEMBRANE_MAX_CHARS = 3000
MEMBRANE_RECENCY_HOURS = 72

# Conversation log (Phase 4 Layer 0)
CONVERSATION_PATH = BASE_DIR / "conversation.jsonl"